WIFI_SSID = ""
WIFI_PASSWORD = ""

MQTT_FEED = ""
MQTT_BROKER = ""
MQTT_PORT = 1883
MQTT_USERNAME = ""
MQTT_PASSWORD = ""

HOMEASSISTANT_AUTO_DISCOVERY_TOPIC = "homeassistant"
HOMEASSISTANT_DEVICE_ID = ""
HOMEASSISTANT_DEVICE_NAME = ""