WIFI_SSID = ""
WIFI_PASSWORD = ""

MQTT_FEED = ""
MQTT_BROKER = ""
MQTT_PORT = 1883
MQTT_USERNAME = ""
MQTT_PASSWORD = ""

HOMEASSISTANT_DEVICE_ID = ""
HOMEASSISTANT_DEVICE_NAME = ""

SOFTWARE_VERSION = "1.0"